language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      script: ./build.sh
      before_deploy: sh zip.sh
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      script: ./build_mac.sh
      before_deploy: sh zip_mac.sh
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      script: ./build.bat
      before_deploy: zip.bat
install: pip3 install -r ./requirements.txt --upgrade
deploy:
  # Github Releases
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: zip/*
    skip_cleanup: true
    draft: true
    on:
      tags: true
