language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      before_deploy:
        - sh ./build.sh
        - sh ./zip.sh
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_deploy:
        - sh ./build_mac.sh
        - sh ./zip_mac.sh
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_deploy:
        - cmd /c ./build.bat
        - cmd /c ./zip.bat
script: echo This is here because travis gets mad if theres no script entry in the config.
install: pip3 install -r ./requirements.txt --upgrade
deploy:
  # Github Releases
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: zip/*
    skip_cleanup: true
    draft: true
    on:
      tags: true
